One-Hot Encoding is a technique used in Machine Learning to convert categorical data into numbers.

// if we do ordinal encoding computer thinks the biggest number has more value that is 2 has more value then 0

HENCE WHY WE DO ONE-HOT ENCODING
| City      | Delhi | Mumbai | Bangalore |
| --------- | ----: | -----: | --------: |
| Delhi     |     1 |      0 |         0 |
| Mumbai    |     0 |      1 |         0 |
| Bangalore |     0 |      0 |         1 |
| Delhi     |     1 |      0 |         0 |

DUMMY VARIABLE TRAP:
The Dummy Variable Trap happens when we use all dummy columns created by One-Hot Encoding, causing redundant informatioN

One-Hot Encoding gives:

| Gender | Male | Female |
| ------ | ---: | -----: |
| Male   |    1 |      0 |
| Female |    0 |      1 |
| Male   |    1 |      0 |
| Female |    0 |      1 |

Notice something:

If we know `Male = 0`, we automatically know:
Female = 1
And if:
Male = 1
Female = 0
So we don't actually need **both columns**.

# 2. Remove one column

| Gender | Male |
| ------ | ---: |
| Male   |    1 |
| Female |    0 |
| Male   |    1 |
| Female |    0 |

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('cars.csv')

In [ ]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [ ]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Kia                 4
Ambassador          4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [ ]:
df['brand'].nunique()

32

In [ ]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

1. ONEHOT ENCODING USING PANDAS

In [ ]:
pd.get_dummies(df,columns=['fuel','owner'])
#we have only 3 columns brand,fuel,owner
fuel column will be removed then new 4 column will come then 8, then owner will be removed then 5 column the total 12 columns will come

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

 DataFrame has only these 3 columns:
brand | fuel | owner
For example:

| brand | fuel   | owner  |
| ----- | ------ | ------ |
| BMW   | Petrol | First  |
| Audi  | Diesel | Second |
| BMW   | Petrol | First  |
| Tata  | CNG    | Third  |

# Step 1: Original DataFrame
brand | fuel | owner
```
3 columns
# Step 2: `fuel` is selected

Pandas first processes:

fuel
```

Suppose `fuel` has **4 different categories**:

```text
Petrol
Diesel
CNG
Electric
```

One-hot encoding creates **4 new columns**:

```text
fuel_Petrol
fuel_Diesel
fuel_CNG
fuel_Electric
```

fuel-> column is removed.

3 - 1 = 2
```

Add 4 dummy columns:

2 + 4 = 6
```

So now there are:

**6 columns.**

---

# Step 3: Now `owner` is processed

Suppose `owner` has **8 different categories**.

For example:

```text
First
Second
Third
Fourth
Fifth
Sixth
Seventh
Eighth
```

One-hot encoding creates:

```text
owner_First
owner_Second
owner_Third
owner_Fourth
owner_Fifth
owner_Sixth
owner_Seventh
owner_Eighth
```

That's **8 new columns**.

The original `owner` column is removed.

So:

Current columns = 6
```

Remove `owner`:

6 - 1 = 5
```

Add 8 dummy columns:

```text
5 + 8 = 13
```

So the final DataFrame has:

**13 columns**, not 12.

2.  K-1 ONE HOT ENCODING

In [ ]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

## 1. Without `drop_first=True`

fuel = Petrol, Diesel, CNG

creates:

| fuel   | fuel_CNG | fuel_Diesel | fuel_Petrol |
| ------ | -------: | ----------: | ----------: |
| CNG    |        1 |           0 |           0 |
| Diesel |        0 |           1 |           0 |
| Petrol |        0 |           0 |           1 |


# 2. What does `drop_first=True` do?

Result:

| fuel   | fuel_Diesel | fuel_Petrol |
| ------ | ----------: | ----------: |
| CNG    |           0 |           0 |
| Diesel |           1 |           0 |
| Petrol |           0 |           1 |

### How do we know CNG?

If:

fuel_Diesel = 0
fuel_Petrol = 0
then it must be:

CNG

So we don't need a separate `fuel_CNG` column.

3. ONE HOT ENCODING USING SKLEARN

In [ ]:
#// in projects we dont use 2nd method because it dont remember the data so we use sklearn

In [ ]:
from sklearn.model_selection import train_test_split

x = df.iloc[:, 0:4]
y = df.iloc[:, -1]

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:
x_train.head()

        brand  km_driven    fuel                 owner
6518     Tata       2560  Petrol           First Owner
6144    Honda      80000  Petrol          Second Owner
6381  Hyundai     150000  Diesel  Fourth & Above Owner
438    Maruti     120000  Diesel          Second Owner
5939   Maruti      25000  Petrol           First Owner

In [ ]:
from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder()
//we will not apply for all will will not apply at brand and km_driven
we will just apply at fuel and owner, we need to remove Fuel and owner separetly and apply One HotEncoder then join a table
which is difficult so we use Column Transformer
but now we will do that method it self we will do Column Transformer later

In [ ]:
ohe=OneHotEncoder()

In [ ]:
ohe.fit_transform(x_train[['fuel','owner']])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 13004 stored elements and shape (6502, 9)>

// 9 column above in output is 4 of fuel and 5 of owner

In [ ]:
ohe.fit_transform(x_train[['fuel','owner']]).toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]], shape=(6502, 9))

In [ ]:
x_train_new=ohe.fit_transform(x_train[['fuel','owner']]).toarray()

In [ ]:
x_test_new=ohe.fit_transform(x_train[['fuel','owner']]).toarray()

NOW I NEED TO REMOVE BRAND, KM_DRIVEN FROM x_train
THEN APPEND TO THE ABOVE ARRAY WHICH WE GOT IN OUTPUT

In [ ]:
x_train[['brand','km_driven']].values

array([['Tata', 2560],
       ['Honda', 80000],
       ['Hyundai', 150000],
       ...,
       ['Hyundai', 35000],
       ['Maruti', 27000],
       ['Maruti', 70000]], shape=(6502, 2), dtype=object)

// now it became numpy array and we already have array above in output

In [ ]:
#APPEND BOTH
np.hstack((x_train[['brand','km_driven']].values,x_train_new))
#Horizontal stack → join things side-by-side (column-wise).

array([['Tata', 2560, 0.0, ..., 0.0, 0.0, 0.0],
       ['Honda', 80000, 0.0, ..., 1.0, 0.0, 0.0],
       ['Hyundai', 150000, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       ['Hyundai', 35000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 27000, 0.0, ..., 0.0, 0.0, 0.0],
       ['Maruti', 70000, 0.0, ..., 1.0, 0.0, 0.0]],
      shape=(6502, 11), dtype=object)

In [ ]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new)).shape

(6502, 11)

4. ONE-HOTENCODING WITH TOP CATEGORIES

In [ ]:
counts = df['brand'].value_counts()
#Count how many times each brand appears

In [ ]:
df['brand'].nunique()
threshold = 100
#nunique() = number of unique values
#If a brand appears 100 times or less, we will consider it uncommon.

In [ ]:
#Find the uncommon brands
#repl is basically a list of uncommon categories.
repl = counts[counts <= threshold].index

In [ ]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
929,False,False,False,False,True,False,False,False,False,False,False,False,False
1155,False,False,False,False,True,False,False,False,False,False,False,False,False
1492,False,False,False,False,False,False,True,False,False,False,False,False,False
1389,False,False,False,False,True,False,False,False,False,False,False,False,False
2667,False,False,False,False,False,False,False,False,False,False,False,False,True

df['brand'].replace(repl, 'uncommon')

Suppose original data is:

BMW
Honda
Ford
Toyota
Skoda
Honda

If Ford and Skoda are uncommon:

BMW
Honda
uncommon
Toyota
uncommon
Honda

So instead of having separate categories:

Ford
Skoda
Renault
...

we combine them into:

uncommon
When do we use it?

When you have many rare categories and want to group them together.